/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package action;

import org.checkerframework.checker.units.qual.h;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException {
        System.out.println(new App().getGreeting());
        click c1=new click();
        c1.launch();
       drag h1=new drag();
        h1.DropandDrop();
        hover h2=new hover() ;
        h2.scrollandhover();
       multipleAction ma=new multipleAction();
       ma.Multi();
       AutoComplete autoc=new AutoComplete();
       autoc.Multi();
        
    }
}
